--
-- PostgreSQL database dump
--

\restrict fKLCQ5aG3oD5L0heGxsJnbt8L5fREkrgI8BCXP8DnxlOeebhn6Iyc6BtbdiZuoW

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg13+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carte_fidelite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carte_fidelite (
    id integer NOT NULL,
    utilisateur_id integer NOT NULL,
    magasin_id integer NOT NULL,
    code_barre integer NOT NULL
);


ALTER TABLE public.carte_fidelite OWNER TO postgres;

--
-- Name: carte_magasin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carte_magasin (
    id integer NOT NULL,
    magasin_id integer NOT NULL,
    rayon_id integer NOT NULL,
    chemin_asbolut text NOT NULL
);


ALTER TABLE public.carte_magasin OWNER TO postgres;

--
-- Name: etage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etage (
    id integer NOT NULL,
    magasin_id integer NOT NULL,
    numero integer NOT NULL
);


ALTER TABLE public.etage OWNER TO postgres;

--
-- Name: magasin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.magasin (
    id integer NOT NULL,
    libelle text NOT NULL,
    longitude double precision,
    latitude double precision,
    chemin_absolut_logo text NOT NULL
);


ALTER TABLE public.magasin OWNER TO postgres;

--
-- Name: magasin_favori; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.magasin_favori (
    id integer NOT NULL,
    utilisateur_id integer NOT NULL,
    magasin_id integer NOT NULL
);


ALTER TABLE public.magasin_favori OWNER TO postgres;

--
-- Name: panier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.panier (
    id integer NOT NULL,
    utilisateur_id integer NOT NULL,
    magasin_id integer NOT NULL,
    code_barre integer NOT NULL,
    total_ttc integer NOT NULL,
    date_heure_creation timestamp without time zone NOT NULL
);


ALTER TABLE public.panier OWNER TO postgres;

--
-- Name: panier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.panier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.panier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produit (
    code_barre bigint NOT NULL,
    rayon_id integer NOT NULL,
    promotion_id integer,
    libelle text NOT NULL,
    image text,
    prix double precision NOT NULL
);


ALTER TABLE public.produit OWNER TO postgres;

--
-- Name: promotion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.promotion (
    id integer NOT NULL,
    magasin_id integer NOT NULL,
    libelle text NOT NULL,
    date_heure_debut timestamp without time zone NOT NULL,
    date_heure_fin timestamp without time zone NOT NULL,
    mode_promotion text NOT NULL,
    quantite_acheter integer,
    quantite_offert integer,
    pourcentage_reduction double precision,
    reduction_fixe double precision,
    caniotte_immediate boolean
);


ALTER TABLE public.promotion OWNER TO postgres;

--
-- Name: rayon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rayon (
    id integer NOT NULL,
    magasin_id integer NOT NULL,
    etage_id integer NOT NULL,
    libelle text NOT NULL,
    point1_x double precision NOT NULL,
    point1_y double precision NOT NULL,
    point2_x double precision NOT NULL,
    point2_y double precision NOT NULL
);


ALTER TABLE public.rayon OWNER TO postgres;

--
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id integer NOT NULL,
    libelle text NOT NULL,
    archivage boolean NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- Name: scan_panier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scan_panier (
    id integer NOT NULL,
    panier_id integer NOT NULL,
    produit_id bigint NOT NULL,
    quantite integer NOT NULL,
    date_heure_creation timestamp without time zone NOT NULL
);


ALTER TABLE public.scan_panier OWNER TO postgres;

--
-- Name: scan_panier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.scan_panier ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.scan_panier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur (
    id integer NOT NULL,
    role_id integer NOT NULL,
    magasin_id integer,
    nom text NOT NULL,
    prenom text NOT NULL,
    mail text NOT NULL,
    mdp text NOT NULL
);


ALTER TABLE public.utilisateur OWNER TO postgres;


INSERT INTO public.magasin (id, libelle, longitude, latitude, chemin_absolut_logo) VALUES
(1, 'Supermarché Test', 2.3522, 48.8566, '/logos/magasin_test.png');

INSERT INTO public.etage (id, magasin_id, numero) VALUES
(1, 1, 0); -- Rez-de-chaussée (numéro 0)

INSERT INTO public.role (id, libelle, archivage) VALUES
(1, 'ADMIN', false);

INSERT INTO public.rayon (id, magasin_id, etage_id, libelle, point1_x, point1_y, point2_x, point2_y) VALUES
(1, 1, 1, 'Boissons', 0, 0, 10, 5);

INSERT INTO public.promotion (id, magasin_id, libelle, date_heure_debut, date_heure_fin, mode_promotion, quantite_acheter, quantite_offert, pourcentage_reduction, reduction_fixe, caniotte_immediate) VALUES
(1, 1, 'Promo boissons', '2026-04-28 11:39:36.81594', '2026-05-28 11:39:36.81594', 'POURCENTAGE', NULL, NULL, 10, NULL, false);

INSERT INTO public.produit (code_barre, rayon_id, promotion_id, libelle, image, prix) VALUES
(1234567890123, 1, 1, 'Bouteille d’eau 1.5L', '/images/eau.png', 1.25);

INSERT INTO public.utilisateur (id, role_id, magasin_id, nom, prenom, mail, mdp) VALUES
(1, 1, 1, 'Doe', 'John', 'john.doe@test.com', 'hashed_password');


--
-- Name: panier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.panier_id_seq', 1, false);


--
-- Name: scan_panier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.scan_panier_id_seq', 1, false);


--
-- Name: carte_fidelite carte_fidelite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carte_fidelite
    ADD CONSTRAINT carte_fidelite_pkey PRIMARY KEY (id);


--
-- Name: carte_magasin carte_magasin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carte_magasin
    ADD CONSTRAINT carte_magasin_pkey PRIMARY KEY (id);


--
-- Name: etage etage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etage
    ADD CONSTRAINT etage_pkey PRIMARY KEY (id);


--
-- Name: magasin_favori magasin_favori_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.magasin_favori
    ADD CONSTRAINT magasin_favori_pkey PRIMARY KEY (id);


--
-- Name: magasin magasin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.magasin
    ADD CONSTRAINT magasin_pkey PRIMARY KEY (id);


--
-- Name: panier panier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panier
    ADD CONSTRAINT panier_pkey PRIMARY KEY (id);


--
-- Name: produit produit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT produit_pkey PRIMARY KEY (code_barre);


--
-- Name: promotion promotion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotion
    ADD CONSTRAINT promotion_pkey PRIMARY KEY (id);


--
-- Name: rayon rayon_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rayon
    ADD CONSTRAINT rayon_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: scan_panier scan_panier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scan_panier
    ADD CONSTRAINT scan_panier_pkey PRIMARY KEY (id);


--
-- Name: utilisateur utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT utilisateur_pkey PRIMARY KEY (id);


--
-- Name: carte_fidelite carte_fidelite_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carte_fidelite
    ADD CONSTRAINT carte_fidelite_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: carte_fidelite carte_fidelite_utilisateur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carte_fidelite
    ADD CONSTRAINT carte_fidelite_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateur(id);


--
-- Name: carte_magasin carte_magasin_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carte_magasin
    ADD CONSTRAINT carte_magasin_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: carte_magasin carte_magasin_rayon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carte_magasin
    ADD CONSTRAINT carte_magasin_rayon_id_fkey FOREIGN KEY (rayon_id) REFERENCES public.rayon(id);


--
-- Name: etage etage_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etage
    ADD CONSTRAINT etage_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: magasin_favori magasin_favori_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.magasin_favori
    ADD CONSTRAINT magasin_favori_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: magasin_favori magasin_favori_utilisateur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.magasin_favori
    ADD CONSTRAINT magasin_favori_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateur(id);


--
-- Name: panier panier_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panier
    ADD CONSTRAINT panier_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: panier panier_utilisateur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panier
    ADD CONSTRAINT panier_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateur(id);


--
-- Name: produit produit_promotion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT produit_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotion(id);


--
-- Name: produit produit_rayon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT produit_rayon_id_fkey FOREIGN KEY (rayon_id) REFERENCES public.rayon(id);


--
-- Name: promotion promotion_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotion
    ADD CONSTRAINT promotion_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: rayon rayon_etage_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rayon
    ADD CONSTRAINT rayon_etage_id_fkey FOREIGN KEY (etage_id) REFERENCES public.etage(id);


--
-- Name: rayon rayon_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rayon
    ADD CONSTRAINT rayon_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: scan_panier scan_panier_panier_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scan_panier
    ADD CONSTRAINT scan_panier_panier_id_fkey FOREIGN KEY (panier_id) REFERENCES public.panier(id);


--
-- Name: scan_panier scan_panier_produit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scan_panier
    ADD CONSTRAINT scan_panier_produit_id_fkey FOREIGN KEY (produit_id) REFERENCES public.produit(code_barre);


--
-- Name: utilisateur utilisateur_magasin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT utilisateur_magasin_id_fkey FOREIGN KEY (magasin_id) REFERENCES public.magasin(id);


--
-- Name: utilisateur utilisateur_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur
    ADD CONSTRAINT utilisateur_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--

\unrestrict fKLCQ5aG3oD5L0heGxsJnbt8L5fREkrgI8BCXP8DnxlOeebhn6Iyc6BtbdiZuoW

